version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.1
    - 3.11.0
    - 3.9.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: "@opd/eslint-config-pangu"
    versions:
    - 1.13.5
  - dependency-name: "@opd/babel-preset-lib"
    versions:
    - 1.13.5
  - dependency-name: "@opd/prettier-config-pangu"
    versions:
    - 1.13.5
  - dependency-name: "@opd/jest-preset-pangu"
    versions:
    - 1.13.5
