

sudo: false
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

install:
  - npm install

script:
  - npm run build

after_success:
  - npm i coveralls -D
  - cat ./coverage/lcov.info | coveralls
